#!/usr/bin/env python

from ultelnet import UlTelnet


def main():
    tel = UlTelnet()
    tel.open("c64")

    print("setting up printer...")
    tel.setup_printer("prints")

    print("loading print master...")
    tel.mount_disk_on_b("print master-d2.d64")

    tel.quit()
    tel.open("c64")

    tel.expect_screen_draw()
    tel.run_disk("print master-d1.d64")

    tel.quit()

if __name__ == "__main__":
    main()
