#!/usr/bin/env python

from ultelnet import UlTelnet


def main():
    tel = UlTelnet()
    tel.open("c64")

    print("flushing print job...")
    tel.flush_printer()

    # TODO: get latest print file via ftp
    # TODO: show in terminal
    # TODO: transform image
    # TODO: print!

    tel.quit()

if __name__ == "__main__":
    main()
