#!/usr/bin/env python

from ultelnet import UlTelnet


def main():
    tel = UlTelnet()
    tel.open("c64")
    print("setting up printer...")
    tel.setup_printer("prints")
    print("loading print shop...")
    tel.run_disk("print shop.d64")


if __name__ == "__main__":
    main()
