#!/usr/bin/env python

import time

import pyfirmata

from print import print_latest


def main():
    board = pyfirmata.util.get_the_board(identifier="tty.usbmodem")

    it = pyfirmata.util.Iterator(board)
    it.start()

    pin = board.get_pin("d:3:i")

    print("the spider 🕷  is ready to print...")

    while True:
        wait_for_pin(pin, True)
        print_latest()
        wait_for_pin(pin, False)
        print("the spider 🕷  is ready to print AGAIN...")


def wait_for_pin(pin, status):
    while True:
        if pin.read() == status:
            return
        time.sleep(0.1)


if __name__ == "__main__":
    main()
