#!/usr/bin/env python

from ulftp import UlFtp
from ultelnet import UlTelnet

ADDR = "c64"
FILENAME = "update.u2l"


def main():
    tel = UlTelnet()
    tel.open(ADDR)
    ftp = UlFtp()
    ftp.open(ADDR)

    print("sending firmware...")
    ftp.send(FILENAME, FILENAME)

    print("starting update...")
    tel.update_firmware(FILENAME)

    # No need to quit - we're rebooting!


if __name__ == "__main__":
    main()
